### ISSUE TITLE
USB ports interfere with each other

### ISSUE THREAD

**Issue by jwise** [jwise/x1-expander#13]

**Comment by bani6809** [comment]
[USB official spec](https://www.usb.org/document-library/usb-20-specification) defines the allowed type A plug overmold dimensions. 

16mm x 8mm would seem to be a good minimum.

![image](https://github.com/jwise/x1-expander/assets/43738861/7d6e1092-208e-48f5-8295-11a3abab54ea)

**Comment by jwise** [comment]
I am thinking that a vertical USB socket would be a good approach to avoid having to change the dimensions of the board.

**Comment by bani6809** [comment]
something like this one then

https://www.lcsc.com/product-detail/USB-Connectors_SHOU-HAN-AF-14-0-CC-T_C456020.html

**Comment by jwise** [comment]
yeah, that looks like a good option

**Comment by bani6809** [comment]
this may be easier to route:
https://www.lcsc.com/product-detail/USB-Connectors_XUNPU-USB-226-BRW_C720524.html

**Comment by jwise** [comment]
hmm though with the EEPROM we can configure the LAN9514 to swap P and N for us, but I will look at that one too
