### ISSUE TITLE
TEST2 and TEST3 are wrong, they are reversed

### ISSUE THREAD

**Issue by bani6809** [jwise/x1-expander#15]
TEST2 and TEST3 are wrong, they are reversed.

![image](https://github.com/jwise/x1-expander/assets/43738861/af271915-a9db-457d-8d25-1667a634e2e1)

reference design:

![image](https://github.com/jwise/x1-expander/assets/43738861/19e76f51-5215-447f-b964-8932a714812c)

![image](https://github.com/jwise/x1-expander/assets/43738861/578c0281-36fa-418d-ae3e-a0f326aa5714)

**Comment by jwise** [comment]
schematic change in e76d6e2
