### ISSUE TITLE
X1P-001: sighting: 24V wires fatigued at X1P-002 end

### ISSUE THREAD

**Issue by jwise** [jwise/x1-expander#67]
May be worth a hot melt or other strain relief at the connector-wire interface?

**Comment by WolfwithSword** [comment]
For reference: 
![image](https://github.com/user-attachments/assets/1e75ba39-aa93-455d-a8e1-5cf6075d9c1a)
![image](https://github.com/user-attachments/assets/af986a40-8f19-4b31-81ad-2d7bd29e33e2)


Edit - after fixing, it also helped a lot to have all the wires about an inch or so up bound together, both as extra strain relief but also it assisted in install of the harness that the wires were not sprawling from the connector end.

**Comment by jwise** [comment]
To be fixed in X1P-001-A03 with silastic glue.

**Comment by jwise** [comment]
fixed in a03
